language: go
go:
  - "1.12"

env:
  - GO111MODULE=on

install: true

jobs:
  include:
    - stage: check with linter
      before_script:
        - curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | sh -s -- -b $(go env GOPATH)/bin vX.Y.Z
      script:
        - golangci-lint run
    - stage: run tests
      script:
        - make test
      after_script:
        - make clean
