language: go
go:
  - "1.12"

env:
  - GO111MODULE=on

install: true

jobs:
  include:
    - stage: check with linter
      before_script:
        - ./linter.sh install
      script:
        - ./linter.sh run
    - stage: run tests
      script:
        - make test
      after_script:
        - make clean
