// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package queues

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjsonFa095a18DecodeGithubComStudtoolCommonQueues(in *jlexer.Lexer, out *DeletedAvatarData) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeString()
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "userId":
			out.UserId = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonFa095a18EncodeGithubComStudtoolCommonQueues(out *jwriter.Writer, in DeletedAvatarData) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"userId\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(in.UserId))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v DeletedAvatarData) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonFa095a18EncodeGithubComStudtoolCommonQueues(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v DeletedAvatarData) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonFa095a18EncodeGithubComStudtoolCommonQueues(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *DeletedAvatarData) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonFa095a18DecodeGithubComStudtoolCommonQueues(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *DeletedAvatarData) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonFa095a18DecodeGithubComStudtoolCommonQueues(l, v)
}
func easyjsonFa095a18DecodeGithubComStudtoolCommonQueues1(in *jlexer.Lexer, out *CreatedAvatarData) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeString()
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "userId":
			out.UserId = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonFa095a18EncodeGithubComStudtoolCommonQueues1(out *jwriter.Writer, in CreatedAvatarData) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"userId\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(in.UserId))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v CreatedAvatarData) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonFa095a18EncodeGithubComStudtoolCommonQueues1(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v CreatedAvatarData) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonFa095a18EncodeGithubComStudtoolCommonQueues1(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *CreatedAvatarData) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonFa095a18DecodeGithubComStudtoolCommonQueues1(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *CreatedAvatarData) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonFa095a18DecodeGithubComStudtoolCommonQueues1(l, v)
}
